### ISSUE TITLE
Feedback: Tooltip behind right click menu

### ISSUE THREAD

**Issue by mastersuleman** [Cyborger1/examine-tooltip#10]
Right now if you examine and the tooltip pops up, its always at the front with the right click menu always being placed behind it so you can't see the right click menu or it interferes with other menus.

Is there a way to have it so that if I right click, the right click menu is always on top?

Even changing the opacity still makes it distracting or hard to read the menu.

Example:
![S9zJ5DB](https://user-images.githubusercontent.com/18666249/212710853-c512d683-9d1a-42be-8f92-fdb8ea76caad.png)

**Comment by Cyborger1** [comment]
I agree this is worth improving. I went ahead and added a config in "Display settings" called "Overlay Layer" that should fix this issue for you.

I had set the tooltips to appear on top of everything "Always On Top" to ensure they never get hidden by something in the game. I still kept this as the default setting with the new config option, but now if you select "Above Widgets", it should render below the right-click menu.

I haven't tested this extensively however, but I doubt it'll create any issues otherwise.

You may keep track of the update PR here: https://github.com/runelite/plugin-hub/pull/3781

I will close the issue once you play with the updated plugin and confirm to me everything's good.

**Comment by Cyborger1** [comment]
Here's what the option looks like in the config, for reference:

![image](https://user-images.githubusercontent.com/45152844/212735726-bee4026c-8e1e-4319-b300-6950d027f420.png)

**Comment by Cyborger1** [comment]
The update should be live now, can you confirm this fixes your issue?

**Comment by mastersuleman** [comment]
Omg this is perfect thank you.
Its working great!
I've commented on changes or updates on so many plugins but you're the first who actually responded and solved it.

Thanks so much man!
